CREATE TABLE IF NOT EXISTS resume_source (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    url                 VARCHAR(1000) NOT NULL,
    source_type         VARCHAR(50),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    last_sync_at        TIMESTAMP,
    last_sync_count     INT DEFAULT 0,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Seed two demo sources pointing at the built-in mock job board
INSERT INTO resume_source (name, url, source_type, active) VALUES
    ('LinkedIn (Demo)', 'http://localhost:8080/mock-jobboard/linkedin/candidates', 'LINKEDIN', TRUE),
    ('JobStreet (Demo)', 'http://localhost:8080/mock-jobboard/jobstreet/candidates', 'JOBSTREET', TRUE);
