CREATE TABLE IF NOT EXISTS mock_job_role (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(255) NOT NULL,
    department      VARCHAR(100),
    location        VARCHAR(100) DEFAULT 'Kuala Lumpur, Malaysia',
    description     TEXT,
    requirements    TEXT,
    requisition_id  BIGINT,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mock_application (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mock_job_role_id    BIGINT REFERENCES mock_job_role(id),
    full_name           VARCHAR(255) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    headline            VARCHAR(255),
    skills              VARCHAR(1000),
    years_experience    DECIMAL(4,1),
    resume_text         TEXT,
    source_channel      VARCHAR(50) NOT NULL DEFAULT 'JOBBOARD',
    created_at          TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Add TalentBoard as a resume source so applications sync into the ATS
INSERT INTO resume_source (name, url, source_type, active) VALUES
    ('TalentBoard (Job Applications)', 'http://localhost:8080/mock-jobboard/applications', 'JOBBOARD', TRUE);

-- Seed sample job roles
INSERT INTO mock_job_role (title, department, location, description, requirements) VALUES
('Senior Software Engineer', 'Engineering', 'Kuala Lumpur, Malaysia',
 'Join our core platform team building scalable backend systems that power millions of transactions.',
 'Java, Spring Boot, microservices, 5+ years experience, strong system design skills'),
('Product Manager', 'Product', 'Kuala Lumpur, Malaysia',
 'Lead product vision and roadmap for our flagship B2B SaaS platform. Work closely with engineering and design.',
 '3+ years PM experience, data-driven mindset, excellent communication, startup experience preferred'),
('Data Scientist', 'Analytics', 'Remote (Malaysia)',
 'Build ML models and data pipelines to drive business insights and product intelligence.',
 'Python, SQL, machine learning, statistics, 2+ years experience'),
('UX/UI Designer', 'Design', 'Kuala Lumpur, Malaysia',
 'Design intuitive user experiences for our web and mobile products. Own the design system.',
 'Figma, user research, prototyping, 3+ years product design experience');
