-- Agentic orchestrator: agent runs and their step-by-step traces

CREATE TABLE agent_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_id  BIGINT,
    candidate_id    BIGINT,
    match_id        BIGINT,
    goal            VARCHAR(1000),
    status          VARCHAR(40) NOT NULL,          -- RUNNING, PAUSED_FOR_APPROVAL, COMPLETED, FAILED, CANCELLED
    pending_tool    VARCHAR(100),                  -- tool awaiting human approval
    pending_input   VARCHAR(65535),                          -- JSON input of the pending tool call
    result_summary  VARCHAR(65535),                          -- agent's final answer
    conversation    VARCHAR(65535),                          -- serialized messages array (for resume after approval pause)
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE agent_step (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id       BIGINT NOT NULL,
    step_no      INT NOT NULL,
    step_type    VARCHAR(40) NOT NULL,             -- THOUGHT, TOOL_CALL, TOOL_RESULT, APPROVAL_REQUEST, APPROVAL_DECISION, FINAL, ERROR
    tool_name    VARCHAR(100),
    content      VARCHAR(65535),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_step_run FOREIGN KEY (run_id) REFERENCES agent_run(id)
);

CREATE INDEX idx_agent_run_requisition ON agent_run(requisition_id);
CREATE INDEX idx_agent_step_run ON agent_step(run_id);
