-- Tracks the outcome of candidate-facing notification emails (rejection,
-- shortlist follow-ups, etc.) so a failed send is visible to recruiters
-- and can be manually resent, instead of silently disappearing while the
-- pipeline/status change that triggered it still succeeds.

CREATE TABLE notification_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id      BIGINT,
    requisition_id    BIGINT,
    notification_type VARCHAR(40) NOT NULL,       -- REJECTION, etc.
    recipient_email   VARCHAR(255) NOT NULL,
    subject           VARCHAR(500),
    body              VARCHAR(65535),              -- rendered HTML, kept so a failed send can be retried verbatim
    status            VARCHAR(20) NOT NULL,        -- SENT, FAILED
    error_message     VARCHAR(1000),
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notification_log_status ON notification_log(status);
CREATE INDEX idx_notification_log_candidate ON notification_log(candidate_id, requisition_id);
