CREATE TABLE app_user (
                          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username        VARCHAR(100) NOT NULL UNIQUE,
                          email           VARCHAR(255) NOT NULL UNIQUE,
                          password_hash   VARCHAR(255) NOT NULL,
                          full_name       VARCHAR(255) NOT NULL,
                          role            VARCHAR(50)  NOT NULL DEFAULT 'RECRUITER',
                          created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job_requisition (
                                 id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 title           VARCHAR(255) NOT NULL,
                                 department      VARCHAR(100),
                                 location        VARCHAR(100),
                                 description     VARCHAR(65535) NOT NULL,
                                 required_skills VARCHAR(65535),
                                 experience_level VARCHAR(50),
                                 status          VARCHAR(30) NOT NULL DEFAULT 'OPEN',
                                 created_by      BIGINT REFERENCES app_user(id),
                                 created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE candidate (
                           id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           full_name       VARCHAR(255) NOT NULL,
                           email           VARCHAR(255),
                           phone           VARCHAR(50),
                           source_channel  VARCHAR(50) NOT NULL DEFAULT 'MANUAL',
                           resume_text     VARCHAR(65535),
                           resume_filename VARCHAR(255),
                           skills          VARCHAR(65535),
                           years_experience DECIMAL(4,1),
                           headline        VARCHAR(255),
                           profile_url     VARCHAR(500),
                           created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_candidate_email ON candidate(email);
CREATE INDEX idx_candidate_source_channel ON candidate(source_channel);

CREATE TABLE sourcing_match (
                                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                candidate_id    BIGINT NOT NULL REFERENCES candidate(id) ON DELETE CASCADE,
                                requisition_id  BIGINT NOT NULL REFERENCES job_requisition(id) ON DELETE CASCADE,
                                match_score     DECIMAL(5,2) NOT NULL,
                                match_rationale VARCHAR(65535),
                                is_proactive    BOOLEAN NOT NULL DEFAULT TRUE,
                                status          VARCHAR(30) NOT NULL DEFAULT 'NEW',
                                created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                UNIQUE (candidate_id, requisition_id)
);

CREATE INDEX idx_sourcing_match_requisition ON sourcing_match(requisition_id);
CREATE INDEX idx_sourcing_match_score ON sourcing_match(match_score);

CREATE TABLE screening_result (
                                  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  candidate_id        BIGINT NOT NULL REFERENCES candidate(id) ON DELETE CASCADE,
                                  requisition_id      BIGINT NOT NULL REFERENCES job_requisition(id) ON DELETE CASCADE,
                                  overall_score       DECIMAL(5,2) NOT NULL,
                                  skills_score        DECIMAL(5,2),
                                  experience_score    DECIMAL(5,2),
                                  culture_fit_score   DECIMAL(5,2),
                                  strengths           VARCHAR(65535),
                                  gaps                VARCHAR(65535),
                                  rationale           VARCHAR(65535),
                                  recommendation      VARCHAR(30) NOT NULL,
                                  is_edge_case        BOOLEAN NOT NULL DEFAULT FALSE,
                                  reviewed_by         BIGINT REFERENCES app_user(id),
                                  reviewer_decision   VARCHAR(30),
                                  reviewer_notes      VARCHAR(65535),
                                  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  UNIQUE (candidate_id, requisition_id)
);

CREATE INDEX idx_screening_requisition ON screening_result(requisition_id);
CREATE INDEX idx_screening_edge_case ON screening_result(is_edge_case);

CREATE TABLE referral (
                          id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          candidate_id        BIGINT NOT NULL REFERENCES candidate(id) ON DELETE CASCADE,
                          requisition_id      BIGINT REFERENCES job_requisition(id),
                          referred_by         BIGINT NOT NULL REFERENCES app_user(id),
                          relationship_notes  VARCHAR(65535),
                          match_score         DECIMAL(5,2),
                          matched_requisition_id BIGINT REFERENCES job_requisition(id),
                          status              VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
                          submitted_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          last_updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_referral_status ON referral(status);
CREATE INDEX idx_referral_referred_by ON referral(referred_by);

CREATE TABLE interview_schedule (
                                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    candidate_id    BIGINT NOT NULL REFERENCES candidate(id) ON DELETE CASCADE,
                                    requisition_id  BIGINT NOT NULL REFERENCES job_requisition(id) ON DELETE CASCADE,
                                    interview_type  VARCHAR(50) NOT NULL DEFAULT 'SCREENING',
                                    proposed_slots  VARCHAR(65535),
                                    confirmed_slot  TIMESTAMP,
                                    status          VARCHAR(30) NOT NULL DEFAULT 'PROPOSED',
                                    notes           VARCHAR(65535),
                                    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE candidate_status_update (
                                         id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         candidate_id    BIGINT NOT NULL REFERENCES candidate(id) ON DELETE CASCADE,
                                         message         VARCHAR(65535) NOT NULL,
                                         channel         VARCHAR(30) NOT NULL DEFAULT 'EMAIL',
                                         sent_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pipeline_stage (
                                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                candidate_id    BIGINT NOT NULL REFERENCES candidate(id) ON DELETE CASCADE,
                                requisition_id  BIGINT NOT NULL REFERENCES job_requisition(id) ON DELETE CASCADE,
                                stage           VARCHAR(30) NOT NULL DEFAULT 'SOURCED',
                                entered_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_by_agent VARCHAR(50),
                                notes           VARCHAR(65535),
                                UNIQUE (candidate_id, requisition_id)
);

CREATE INDEX idx_pipeline_stage_requisition ON pipeline_stage(requisition_id);
CREATE INDEX idx_pipeline_stage_stage ON pipeline_stage(stage);

CREATE TABLE agent_activity_log (
                                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    agent_name      VARCHAR(50) NOT NULL,
                                    candidate_id    BIGINT REFERENCES candidate(id) ON DELETE CASCADE,
                                    requisition_id  BIGINT REFERENCES job_requisition(id) ON DELETE CASCADE,
                                    action          VARCHAR(100) NOT NULL,
                                    details         VARCHAR(65535),
                                    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_activity_log_agent ON agent_activity_log(agent_name);
CREATE INDEX idx_activity_log_created ON agent_activity_log(created_at);