CREATE TABLE offer (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id     BIGINT NOT NULL,
    requisition_id   BIGINT NOT NULL,
    salary_amount    NUMERIC(12, 2),
    currency         VARCHAR(10) DEFAULT 'MYR',
    start_date       DATE,
    expiry_date      DATE,
    status           VARCHAR(20) DEFAULT 'PENDING',
    notes            TEXT,
    created_at       TIMESTAMP
);
