CREATE TABLE offer_negotiation_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id        BIGINT NOT NULL,
    round_number    INT NOT NULL,
    salary_amount   NUMERIC(12, 2),
    currency        VARCHAR(10),
    start_date      DATE,
    notes           TEXT,
    changed_by      VARCHAR(20) DEFAULT 'RECRUITER',
    created_at      TIMESTAMP
);
