ALTER TABLE referral ALTER COLUMN referred_by SET DEFAULT NULL;
ALTER TABLE referral ALTER COLUMN referred_by DROP NOT NULL;
ALTER TABLE referral ADD COLUMN IF NOT EXISTS referrer_email VARCHAR(255);
